version: "3.9"
services:

  ui:
    image: ui:dev
    build:
      context: ./ui
      target: developement
    volumes:
      - ./ui:/usr/src/app
      - ui_node_modules:/usr/src/app/node_modules
    environment:
      - EXPOSED_PORT=${UI_EXPOSED_PORT}
    ports:
      - ${UI_HOST_PORT}:${UI_EXPOSED_PORT}

  api:
    image: api:dev
    build:
      context: ./api
      target: developement
    volumes:
      - ./api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    environment:
      - EXPOSED_PORT=${API_EXPOSED_PORT}
    ports:
      - ${API_HOST_PORT}:${API_EXPOSED_PORT}

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./.mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/

volumes:
  api_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/api/node_modules
  ui_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/ui/node_modules
